game_of_life_raylib: game_of_life_raylib.c
	cc -o game_of_life_raylib -Ofast game_of_life_raylib.c $$(pkg-config --cflags --libs raylib)

# cc -o game_of_life_raylib -O0 -Wall -g game_of_life_raylib.c $$(pkg-config --cflags --libs raylib)